directory: ~/Music
import:
    incremental: yes
    move: no
    copy: no
    write: yes
ignore_hidden: yes
plugins: lyrics fetchart embedart info mbsync fish musicbrainz
lyrics:
    auto: yes
    keep_synced: yes
    synced: yes
fetchart:
    auto: yes
embedart:
    auto: yes
    ifempty: yes
