-- local treesitter_status_ok, treesitter = pcall(require, "nvim-treesitter.configs")
-- if not treesitter_status_ok then
-- 	return
-- end
-- treesitter.setup({
-- 	ensure_installed = {
-- 		"python",
-- 		"lua",
-- 		"vim",
-- 		"json",
-- 		"yaml",
-- 		"toml",
-- 		"regex",
-- 		"html",
-- 		"css",
-- 		"javascript",
-- 		"bash",
-- 		"norg",
-- 		"http",
-- 		"sql",
-- 		"ruby",
-- 	},
-- 	highlight = {
-- 		enable = true,
-- 		additional_vim_regex_highlighting = false,
-- 	},
-- 	indent = {
-- 	  enable = true,
-- 	  disable = {"python"}
-- 	}
-- })
