local set = vim.opt
vim.g.mapleader = " "
vim.g.maplocalleader = " "
set.mouse = "a"
set.number = true
set.relativenumber = true
set.scrolloff=7
set.hlsearch = false
set.ignorecase = true
set.list = true
set.listchars = {tab = '▸ ', trail = '·'}
set.termguicolors = true
set.autochdir = true
set.updatetime=500
-- set.fileformat = "unix"
set.undofile = true
set.cursorline = true
set.smartindent = true
set.tabstop = 2
set.shiftwidth = 2
set.expandtab = true
set.guifont = {"Iosevka"}
-- set.foldenable = false
set.foldmethod = "expr"
set.foldexpr = "nvim_treesitter#foldexpr()"
set.foldlevel = 99
set.conceallevel = 3
